### ISSUE TITLE
Error on import xetrapal

### ISSUE THREAD

**Issue by arjunvenkatraman** [suryaveer5320129/xetrapal#2]
/usr/local/lib/python2.7/dist-packages/telegram/ext/__init__.py in <module>()
     19 """Extensions over the Telegram Bot API to facilitate bot making"""
     20 
---> 21 from .dispatcher import Dispatcher
     22 from .jobqueue import JobQueue, Job
     23 from .updater import Updater

/usr/local/lib/python2.7/dist-packages/telegram/ext/dispatcher.py in <module>()
     31 from future.builtins import range
     32 
---> 33 from telegram import TelegramError
     34 from telegram.ext.handler import Handler
     35 from telegram.utils.promise import Promise

ImportError: cannot import name TelegramError

**Comment by suryaveer5320129** [comment]
Try with sudo pip install -U python-telegram-bot

**Comment by arjunvenkatraman** [comment]
sudo -H pip uninstall telegram
sudo -H pip install -U python-telegram-bot

Had to uninstall telegram first. Looks like this is related to https://github.com/Tkd-Alex/Telegram-InstaPy-Scheduling/issues/13
